In [2]:
import copy
import time
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

In [3]:
A = np.matrix('0 0 0 3; 3 4 5 6')
B = np.matrix('1 2;3 4; 5 6; 7 8')

In [4]:
A * B

matrix([[ 21,  24],
        [ 82, 100]])

In [43]:
# def simple_way(a, b):

C = np.empty((A.shape[0], A.shape[0]))

for ra in range(A.shape[0]):
    for cb in range(B.shape[1]):
        v = 0
        for ca in range(A.shape[1]):
            v += A[ra, ca] * B[ca, cb]
        
        print(v)
        C[ra, cb] = v
        
C

21
24
82
100


array([[  21.,   24.],
       [  82.,  100.]])

In [14]:
len(A)

2

In [25]:
A.shape

(2, 4)

In [38]:
b = np.empty((2, 3))
b

array([[-4.17871859,  0.        , -0.32768282],
       [ 0.        ,  0.47662355,  0.        ]])

In [36]:
b[0]

1